### ISSUE TITLE
Add high score feature

### ISSUE THREAD

**Issue by jessepinho** [henryefranks/Pac-Bar#1]
It is the only way to properly demonstrate my Pac-Bar prowess, as illustrated here:

![image](https://cloud.githubusercontent.com/assets/1121544/21121825/e3ef37a0-c0ce-11e6-8aba-4bdc18e69680.png)

**Comment by henryefranks** [comment]
I've (finally) added this alongside Swift 4 conversion in commit 23a2fca.
