### ISSUE TITLE
Locked up my whole machine

### ISSUE THREAD

**Issue by billford** [henryefranks/pac-bar#2]
No idea why, touchbar went non-responsive, mouse still moved but couldn't get focus on any windows had to power cycle to get it back. Just figured I'd report it.

**Comment by timtorres** [comment]
Doesn't work on Mac 10.15.1
![image](https://user-images.githubusercontent.com/7048745/71002942-44ddb400-20ae-11ea-8c69-1edd7d325b8f.png)

**Comment by henryefranks** [comment]
As this is the only report I've had of this problem (and it's been a while too), I'm going to go ahead and close this issue.
