### ISSUE TITLE
Doesn't work on latest version of MacOS (10.15.1)

### ISSUE THREAD

**Issue by timtorres** [henryefranks/pac-bar#7]
![image](https://user-images.githubusercontent.com/7048745/71003003-5f179200-20ae-11ea-8fa5-6351f7d72946.png)

**Comment by henryefranks** [comment]
Hey @timtorres, I've recompiled on 10.15.2 and issued it as a new release ([here](https://github.com/henryefranks/pac-bar/releases/tag/v1.2)). Hopefully this should fix the problem, give it a go and let me know if it works.

**Comment by Ministevejobs** [comment]
For some reason the same notice pops up on my screen as Tim Torres.  I even downloaded latest version

**Comment by henryefranks** [comment]
Unfortunately, it looks like this requires a paid Apple developer account, which I cannot afford; you should still be able to run the app from the right-click menu though. This means the issue is closed for now, sorry I couldn't fix it.
